// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSqUaZy-XYiuzShKR9aSMjCeXz__wEBc',
    appId: '1:40318978728:web:44bb7160fdecd01a92509d',
    messagingSenderId: '40318978728',
    projectId: 'flutter-pos-3eb74',
    authDomain: 'flutter-pos-3eb74.firebaseapp.com',
    storageBucket: 'flutter-pos-3eb74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGi5f_GCLwyGAIp9SD3mhleXR-SxCcRJc',
    appId: '1:40318978728:android:b1e076e29f1905d492509d',
    messagingSenderId: '40318978728',
    projectId: 'flutter-pos-3eb74',
    storageBucket: 'flutter-pos-3eb74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDokzvkk032CiNGGkUJGwPjGyHa1dxLuN0',
    appId: '1:40318978728:ios:d84c6fe284dd599f92509d',
    messagingSenderId: '40318978728',
    projectId: 'flutter-pos-3eb74',
    storageBucket: 'flutter-pos-3eb74.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDokzvkk032CiNGGkUJGwPjGyHa1dxLuN0',
    appId: '1:40318978728:ios:d84c6fe284dd599f92509d',
    messagingSenderId: '40318978728',
    projectId: 'flutter-pos-3eb74',
    storageBucket: 'flutter-pos-3eb74.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxSqUaZy-XYiuzShKR9aSMjCeXz__wEBc',
    appId: '1:40318978728:web:6f4e9753918bd65692509d',
    messagingSenderId: '40318978728',
    projectId: 'flutter-pos-3eb74',
    authDomain: 'flutter-pos-3eb74.firebaseapp.com',
    storageBucket: 'flutter-pos-3eb74.firebasestorage.app',
  );
}
